server{
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://parser-container:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Увеличение лимитов для больших запросов
    client_max_body_size 10M;
    
    # Логи для отладки
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}