events {
    worker_connections 1024;
}

http {
    geo $is_ru {
        default 0;
        include /etc/nginx/geoip/ru.zone;
    }

    # Map для выбора бэкенда или заглушки
    map $is_ru $backend {
        default "http://parser-container:5000";
        1       "http://127.0.0.1:80";  # фиктивный, не используется
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            if ($is_ru) {
                rewrite ^ /blocked.html last;
            }
            proxy_pass http://parser-container:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /blocked.html {
            root /usr/share/nginx/html;
        }

        client_max_body_size 10M;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }
}